Feat/room service
pw-software-engineering/b-team pull request #205
Opened 2021-04-20 21:10 UTC by mailo001

2021-04-21 10:33 UTC, Gloomwidow requested changes

2021-04-21 10:33 UTC, Gloomwidow commented on server/cmd/room-service/service.go
> +func roomValid(room bookly.Room) error {
`ValidateRoom` is a better name for this function. `roomValid` doesn't tell us exactly what this function does.

2021-04-21 10:33 UTC, Gloomwidow commented on server/cmd/room-service/service.go
> +// CreateRoom implements valid of adding room
This comment is wrong. It does not implement `valid`, since `roomValid` does it. It validates room details and then it send request to storage to add room.

This comment should be like: `//CreateOffer validates requested room and adds it storage`

2021-04-21 10:33 UTC, Gloomwidow commented on server/cmd/room-service/service.go
> +func toPages(rooms []*bookly.Room, pageNumber int, pageSize int) ([]*bookly.Room, error) {
Good that you implemented that function. I also implemetented that in a package that everyone can use. 
I propose that once my PR will be merged, we will change that to my implementation.

Advantages for that approach:
- We don't copy the same code.
- If something is wrong in paging, we need to fix only one file.
- Tests for paging can be done for one file. No need to test paging in other files.

2021-04-21 10:33 UTC, Gloomwidow commented on server/pkg/bookly/room.go
> +type RoomResponse int
That enum type should be replaced with `error` and returned in functions as `error`.

Fo instance: instead of `RoomNotFound` you could return `ErrorRoomNotFound = err("room not found")`

Right now, your functions return the same thing:
- RoomResponse, which will say if room adding was success or there was an error
- error, which will inform, if there was an error while doing request

You should replace those enums with errors, so we will have the same style of detecting errors in all modules.

2021-04-25 20:59 UTC, areknoster commented on server/pkg/bookly/room.go
> +var ErrRoomAlreadyExists = errors.New("room already exists")
Very good changes :)

2021-04-25 21:02 UTC, areknoster commented on server/pkg/postgres/room_storage_test.go
> +	require.Equal(t, bookly.ErrRoomNotBelongToHotel, err)
`assert.ErrorIs(t, err, bookly.ErrRoomNotBelongToHotel)` would be more appropriate. Same with cases above

2021-04-25 21:05 UTC, areknoster commented on server/pkg/postgres/room_storage.go
> +
You already have it implemented in GetRoom, why don't you just call that function in service and check? I think having no two rooms with the same number is a part of buinsess logic, so it should reside in service "level". Storage should be stupid and just attempt to create the room

2021-04-25 21:08 UTC, areknoster commented on server/pkg/postgres/room_storage.go
>  // CreateRoom implements business logic of create room
I wouldn't say that storing is business logic, it's just keeping stuff until we need them. The checking of room number should thus be moved to service. This would also prevent us from code repetition (we have that select in GetRoom!).

2021-04-25 21:15 UTC, areknoster commented on server/cmd/room-service/service.go
> +func (r *roomService) GetAllHotelRooms(ctx context.Context, hotelID int64, pageNumber int, pageSize int, filter string) ([]*bookly.Room, error) {
Since we always pass `pageNumber int, pageSize int` together, we could got to `paging` package and create `PageInfo` struct with them. Also, there could be `NewPageInfo(pageSize, pageNumber) (PageInfo, error)` contructor, which would validate, if the input is correct. This way we would save some code in the future

2021-04-25 21:17 UTC, areknoster commented on server/pkg/postgres/room_storage.go
>      SELECT *
same as above, we once again break the DRY rule. Checking if it exists is business logic, and we place business logic in service

2021-04-25 21:17 UTC, areknoster commented on server/pkg/postgres/room_storage.go
>  // DeleteRoom implements business logic of delete room
it's storage, storage is responsible for storing, not bot business logic

2021-04-25 21:44 UTC, Gloomwidow commented on server/cmd/room-service/service.go
> +func (r *roomService) GetAllHotelRooms(ctx context.Context, hotelID int64, pageNumber int, pageSize int, filter string) ([]*bookly.Room, error) {
Good idea, I can add that to my paging package next time.

2021-04-26 13:52 UTC, mailo001 commented on server/pkg/postgres/room_storage_test.go
> +	require.Equal(t, bookly.ErrRoomNotBelongToHotel, err)
Ok, I will correct it

2021-04-26 15:19 UTC, areknoster approved these changes

2021-04-26 16:09 UTC, merged