Feat/update offer status implementation
pw-software-engineering/b-team pull request #69
Opened 2021-03-18 21:50 UTC by Gloomwidow

2021-03-18 22:01 UTC, areknoster requested changes
Overall very good job. 
The fact, that we have different formatting shows, why we should add goalng lint to CI

2021-03-18 22:01 UTC, areknoster commented on server/pkg/rently/offer.go
> +	UpdateOfferStatus(ctx context.Context, offerId int64, isActive bool, isDeleted bool) error
That signature is questionable, because we are passing same information twice. Maybe sth like 
```
UpdateOfferStatus(ctx context.Context, offerId int64, isActiveStatus bool) error
```

2021-03-18 22:16 UTC, Gloomwidow commented on server/pkg/rently/offer.go
> +	UpdateOfferStatus(ctx context.Context, offerId int64, isActive bool, isDeleted bool) error
Ok, I changed that in next commit

2021-03-20 10:06 UTC, areknoster approved these changes

2021-03-20 11:36 UTC, merged